# Generated by Django 5.0.4 on 2024-05-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usertwofactorauthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.usertwofactorauthdata'),
        ),
    ]
