# Generated by Django 5.0.4 on 2024-05-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_two_factor_auth_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_auth_data',
        ),
        migrations.DeleteModel(
            name='UserTwoFactorAuthData',
        ),
    ]
